### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by camjac251** [thisispiggy/gmusicchecker#1]
I discovered this script and think it's great. I wish I had found it sooner since probably now some songs are likely gone from my playlist if they get removed. I tried to run it following the README but it might be out of date, starting with the newer named musicchecker vs gmusicchecker. I haven't been able to figure out how to login though since entering my info as arguments don't work. I tried the only gmusicchecker in the history but it also didn't work.

```batch
python musicchecker.py
C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access C:\Users\Me\AppData\Local\Simon Weber\gmusicapi\mobileclient.cred: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
2019-02-26 22:10:05,848 - gmusicapi.Mobileclient1 (shared:183) [WARNING]: could not retrieve oauth credentials from ''C:\\Users\\Me\\AppData\\Local\\Simon Weber\\gmusicapi\\mobileclient.cred''
Traceback (most recent call last):
  File "musicchecker.py", line 96, in <module>
    main()
  File "musicchecker.py", line 79, in main
    mylibrary = getlibrary()
  File "musicchecker.py", line 23, in getlibrary
    library = G.get_all_songs()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\clients\mobileclient.py", line 278, in get_all_songs
    updated_after=updated_after)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\clients\mobileclient.py", line 2053, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\clients\mobileclient.py", line 2053, in <listcomp>
    return [s for chunk in generator for s in chunk]
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\clients\mobileclient.py", line 2067, in _get_all_items_incremental
    **kwargs)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\clients\mobileclient.py", line 48, in _make_call
    return super(Mobileclient, self)._make_call(protocol, *args, **kwargs)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\clients\shared.py", line 90, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\protocol\shared.py", line 213, in perform
    response = session.send(req_kwargs, required_auth)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\gmusicapi\session.py", line 113, in send
    raise NotLoggedIn
gmusicapi.exceptions.NotLoggedIn
```

**Comment by kangruixiang** [comment]
Hey sorry gmusicapi now uses oauth for login instead of you putting in the username and password. I updated the files and README. You should now only need to double click on musicchecker.py.
